using Test
include("../src/SimulateDynamics.jl")
include("../src/GenerateGraphs.jl")
include("../src/ReduceNetwork.jl")
include("../src/Partition.jl")
include("../src/EvaluateError.jl")
include("../src/visualize_landscape.jl")
#include("SimulateDynamicsTest.jl")
#include("GenerateGraphsTest.jl")
#include("ReduceNetworkTest.jl")
#include("EvaluateErrorTest.jl")
include("VisualizeLandscapeTest.jl")
